llm:
  openai:
    provider: "openai"
    model_name: "o4-mini"
  groq:
    provider: "groq"
    model_name: "llama-3.1-70b-versatile"
  gemini:
    provider: "google"
    model_name: "gemini-2.0-flash"
